### ISSUE TITLE
When new releases will be available in rubygems.org?

### ISSUE THREAD

**Issue by ragrum** [stripe/einhorn#55]
I'm using Einhorn installed via `gem install einhorn`, but it seems new releases after `0.6.4` version are not yet available, do you know when they will be?

**Comment by jemc** [comment]
*Bump*

I'd also like to see the latest releases become available through RubyGems.

**Comment by matthewarkin** [comment]
@gdb

**Comment by nelhage** [comment]
Sorry about that! I've just pushed 0.7.1 to rubygems, as well as 0.6.5.

**Comment by jemc** [comment]
Thanks!
