### ISSUE TITLE
Any plans to publish v0.7.5 to rubygems.org?

### ISSUE THREAD

**Issue by ragrum** [stripe/einhorn#69]
Hi, do you have plans to publish v0.7.5 to rubygems.org?

Thanks.

**Comment by leafle** [comment]
Or v0.7.7 or v0.7.8?

**Comment by rafbm** [comment]
The README is very clear about Einhorn being in maintenance mode and that is totally fine. One thing that isn’t clear though is why new versions are pushed (see the recent [0.7.14](https://github.com/stripe/einhorn/commit/b7dc737d82bd056855f42c5f8a1b7f54869604b1) and [0.8.0](https://github.com/stripe/einhorn/commit/96950ecb1e1a78a6338abffacd528761709d2c43#diff-ec6012197db7364c0cd16e3477d78ad8)) but not published to Rubygems.

Again it’s totally fine if the Einhorn team does not want to spend efforts releasing to Rubygems, but can you guys just communicate whether we are expected to stick to the latest released 0.7.4 for some reason, or if the right thing would be to point our Gemfiles to this GitHub repo? In the latter case, maybe adding a note to the README would be good?
